# Generated by Django 3.0.4 on 2022-01-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=2000)),
                ('instructions', models.CharField(max_length=20000)),
            ],
        ),
    ]
