# Generated by Django 3.0.4 on 2022-01-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='ingredients',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='instructions',
            field=models.TextField(max_length=20000),
        ),
    ]
