apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomrecipe
  annotations:
    {}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-randomrecipe
  namespace: default
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-randomrecipe
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-randomrecipe
    spec:
      containers:
      - image: markusdhs/randomrecipe:v1.2
        imagePullPolicy: Always
        name: container-0
        ports:
        - port: 80
          name: test
          targetPort: 80
          nodePort: 30000
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  replicas: 3
