apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomrecipe
  annotations:
    {}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-randomrecipe
  namespace: default
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-randomrecipe
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-randomrecipe
    spec:
      containers:
        - imagePullPolicy: Always
          name: container-0
          __active: true
          image: markusdhs/randomrecipe:v1.2
          ports:
            - name: port
              expose: true
              protocol: TCP
              containerPort: 80
              _serviceType: NodePort
              _ipam: dhcp
              _listeningPort: 30000
  replicas: 3
