name: test

on:
  pull_request:
    branches: [ '**' ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: touch test
    - run: echo "Bla" > test
    - name: Cache test
      id: test
      uses: actions/cache@v3
      with:
        path: ./test
        key: test


  delivery:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - run: cat touch
    - name: Cache test
      id: test
      uses: actions/cache@v3
      with:
        path: ./test
        key: test
