name: test

on:
  pull_request:
    branches: [ '**' ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo chmod 777 -R /var/lib/docker/image/
    - name: Cache test
      id: test
      uses: actions/cache@v3
      with:
        path: /var/lib/docker/image/
        key: test-${{github.event.pull_request.head.sha}}
    #- run: touch test
   # - run: echo "Bla" > test
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t randomrecipe
    - run: sudo ls /var/lib/docker/image/overlay2/imagedb/content/sha256
    - run: sudo docker images
    - run: sudo chmod 755 -R /var/lib/docker/image/

  delivery:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - name: Cache test
      id: test
      uses: actions/cache@v3
      with:
        path: /var/lib/docker/image/
        key: test-${{github.event.pull_request.head.sha}}
    - run: sudo chmod 777 -R /var/lib/docker/image/
    - run: sudo systemctl restart docker
    - run: sudo docker images
   # - run: cat test
    - name: Login to Dockerhub
      env: 
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login --username markusdhs --password "$password"
    - name: Tag the Docker image
      run: docker tag randomrecipe markusdhs/randomrecipe:latest
    - name: Push the Docker image
      run: docker push markusdhs/randomrecipe:latest
   
